---
# gitleaks muat ignore this
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: datavault-secret
  namespace: datavault-dev
spec:
  encryptedData:
    API_KEY: AgAVrRCCZrupQEIYjJGk+bQOw/S5q7p/zxU79d4JjFYBwn/CEmE4m5WAWOyjTrYAMP4rLsUQ9QFVLL8hm04Vdaq/PVUfGiHmSguSaSGxqDndYMlRxMdkW3eX0f+Yz2gVlwE64Fh03C0K5C/8qUdeufdC5tCN8Dar9Rhqg+aLvC6yO6zWP4Avo9T2FR+zcynVyaZtyT1SmqJL6DbCqO8aieQ8owB0+RoIkTXBeaB1nJ1qZanmPJPB1J+ZMyqvefB3OnToqdsWQwWWxb8IOqrJ7h1W9qtF+0j1WyZKLvxzAcU3i9630u95cVfZjz7AvdvmlYE3JymFvlFtkY9e+iVvVi0CJaGOvaYF+vD6ULE9dMiO8lZPHHL9ZqPQIUQdySrGmi8EBDHN88JLqLg1q0UeV3oGSGzuNXi5MkF2fnIcjkP+kgvAj6Xp06V0mGCDK38jyaL5M1n9mecAYyK2aulswsLyZZQ1LSFddwUkz+eyJs+0pTjr/Sjf6a6NlcSUuTSfUFbGRNFhkbQW6Sp1bdZ3W1iK1u1McoFC6OsYrZBMGUaqS/G6HCMZZDFNdCIWjFNC4Jv7Lss/v6qH4Nn78CwyQec4SL5MnqYVGT+Aob0VDbXFkAjZ2K+WYSdDX6Yutef7lUCU2SlFUrGHYWN2rKkoqJXzITNr+JudYnKUktlJnnDvtLMCf8Ly/oyec1Az+p3Uar1xyoS52jF7B4GRdAJjTfjmKw==
    DB_URL: AgAZEV3EZJrDcaycGSvZxA3dKnZYTHr3cbwV8PiRmcvyETr7unp80QzuRUbbKFL6AyPtOmQfHR1W8f6NbS06PK5ihmOPiHNPFdw5Ivjx5wtZoWBSpU+vC+Vxi7XzjkoXYIT90HGFl225H8biPPZZPbCaWgt0nGegFJzdXuWiTLAtpVuK06Lr59IzUrHorFOaIqLcxQHCVQWya4SjLlS1HA09Ppt09EbibSzYYKgiFCnqtWbdOeDRsbRJcrLs4dh9dF9UPvDV4R0rBPSY/AIrVFH0CezaXt5s8KIjKUaPZkeCKQHnPhSdIVhPbLt20jKW2I7IZlurVYNiRUkV99TsQjIz1rs4ehH0GRAn91lLXl0IaJrBD5dKTEY4MCbnyVoXkRAGxQ9S2jX4amKNRx/Kixt6SqOdHhVbfRXpMLfQjZAl9lCHCCyEwnyUVCgmW4b5p7N1ILfqMMZiazKOZWQfCLkjZ6S6PfeIOG3x+giWv+rSVuYZpveWjHJTaNqDelszn4jyv04mxwHlEaOHvk5U3AkQLaDcWqZyak4/fXL+w7k6RRuNM/ekE9B3sKz9KGlLfx9siVZgzxlMmv/W6TswCdVWGw+PWj5Aw1Qg8RIZMr9ZEvWG4qPphnyk6D4x+hEjG0Z+uMJe3bQ2xanLKGAjPhdhDUmOtP3MM/OYD2SzwdOxCXAFGR+/lbGEGubI2ROQZ7jcycDw+wyfGsuHuQAJIhulw0X//esoAX7XKE8C/WtnrN1fsjtp271IW2BkppKBmnioptpjfnLZblS3nHf5SBcrAsg=
  template:
    metadata:
      labels:
        app: datavault-api
        managed-by: kubectl
      name: datavault-secret
      namespace: datavault-dev
    type: Opaque
