---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: datavault-secret
  namespace: datavault-dev
spec:
  encryptedData:
    API_KEY: AgAJ6VkgIcbVJnQZgsvYRO0fLQt/+5txhWMNy51KqS8huLD34WxU5XxcFceFy/TV7i3JSf6XWGdx/8EBASy6mePky9FBKSSd3QX0kzXWKxSeLg1Xkkw9qmqH62+wp4XFx5SLvHkSIseiBV+QigqXZ6a6PPNjUOObJylI4dquF1lv2BfjweYqxJ5Q/AQUWXO1VT6XvB4Ew8IDY7tlVHKb4oirY4TVwGRS/ns4RNKd3Pz7M6zmqXGUuaEoCkJo0bKcp+CqpT92IpnMMhijpgK2LCyaGXfKyznqxXH/3xnoVH5HGlnm5RxgiOAv4U4axsCC5xB2g9SEm5FIT4q1KZM3HyeK47uZKtbBEUrQBFodHRjWTUqUqRzbEsKCfGyR+mlWhaHGTOdkY51D6fdz1U58XEhkwsz/86KvIDdNu7a2mwysQcbtVbwRYopYFx7uDiH3KYSAqRgQeJnaYHy7KoM0kU8I/TL7oFy8EafJgRjzhL5bTdEcMxbcZmQZhNBQx/bcCLGnWQwJ6MvwLh6NgA35tFDcYCaGyPIXEY6hKcphjFwYu4H5MoMD1FBe5dT/U8cqWqS0TJDhLzRvQG3KL29NoPmM3uJvPjEy9PT31tCcEAIipf9Y6mtMrANuKkbllqDafYpK/gLkJ/W7V0dUPFaFtBtH91oIbNfVVUkpSDVQb4G2YEq3S/bAmwnYwZpXSPv1+hA+RWRSntsQOxtCD9MwDdcEkw==
    DB_URL: AgAgwu6Vs1n5CjzxzHiHadj9XQNSYqUSjjDQzl4q0KP6i3/NL2aJyqBr6gKFH437jNS8WgE1pxoG0MoG6xCvXV1hwv31LTecBrulo4FTtC3SBBqLy8VQttm8FHr/EPsAZ1RZ41TxmwUasVX/7us5XlR2GCEgPxZIk7WlThI2G+W0S7qhbCHpHixzxGYu/EZPkHgcnalpMtknL19L0E8YOStC3WbZ1QDR27Du4CTmizDEIxT8ZV33YAi8aPIFypd7Ui+rXbbBoZEsUpyKJgwQPSu+K7jCWA54cU9/yfvrGpg/MsCtZamBP71CvOUd3QggBFDZPSsaj8x58zssjuwLGVCm7288Vce3jclAH93YNodXLjgSJz5EaMlKaEmlVbYcStOd/FtS85puFGJDkc9gGRVwXmjVFH2fU94lapuIoFjYc6KKrDLn4owWx/Kb0BAo93oSzmIGkikqvVAqGTqq2olqqnU2z+rr1yOV2g8mIU5hauhv/0Uf8tz7DzPzd3KfXdgay3LGPYcpoR387QNeMa9m6PfvRl7MiU56w8swWL8OO3Z+U2upZlLHMFmk/hx/M6T0Dg4+dIxuNq9lYRwtIvEMsVX3132yx8zfTTDMBWweoXZujTNOIatC7H5qhN41Pop7GZ7rCD2bA6Ol8QmVXoypoJAB4FQiGU2tCAwiF+lLMRnCmPlp1KGJ38PpNmr9BHaiHKi9Jd1yOqmlvLLVP0c0euTGb1WgtlkKxcvUuxFzWAXTcfjAKmS913CTo7EFG7obby3a8I2V/mhp+agtzgYe1cM=
  template:
    metadata:
      labels:
        app: datavault-api
        managed-by: kubectl
      name: datavault-secret
      namespace: datavault-dev
    type: Opaque
