---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: datavault-secret
  namespace: datavault-dev
spec:
  encryptedData:
    API_KEY: AgA78PzFlFaHQtrC3txFHIB+WzaXuQ/nuGBA6QVa3pQEcynoocnzbxUGQet4nULP2EhZdAWykdJxD72DPHkUud0TrMBg+8tg4KCxG4EqF7/6XurCSXVUFZJnfxUg/jZVqxkEmIstvc+VDl1j/RQhX5o5hQOADUv0DlLYNTvvCQMJaVtU++1mbskzHs6Bo+f1SV6RbCMdHmCNPw9itKurahLMOI18x5BQwGPPYJhpmvgt8L/GBAmR2fnTrkH+IxMopHXDusxrCz/jrGuoC3qy4WrIKe0tFOKOEtUkvM2sbPlGls5Np3E5WDvC0U+f00HHjbIHpQ6RFjF0aOPUcdIF0J1mZM6N6ex+4lF8YeR2PoCupGPHERS4x9OYIip1T4m+5sZyILhHRxO+gm9gIRr4aoyk+JuncFeXr8CdC+Pq/ig+6yqddLD5XFxr8zJBtJY+dyNEkHM5wToBY5SJczZ2Ry16U7uf8i6jHs8iyICEE9UXtWIayo7BIE75F8mi4e9FIPSqY1DSOt93/y5UxHDrY7t7y6z7EK9Iy8VKBnOL4zKYkzAw7xQ0SBL67yc2iL9knywo4zBS4dJK8oIrregqNjM2og9cP1AdIUHmvgciCFfGvA+M+UU8pg1jBtpR0MTHmNnoYKeKhnStQgR3f1EPdKo7zDcvhAIEKvsdjEwQEaz77PEgBXNFGBdhpvGE6sJy6IPdw3bKXm0XjvFQ8y8E3kBelA==
    DB_URL: AgAnxxv4e3RvvJvgq3CnpxDjTXVfHywN09gM76uz9vh8GTFR8f+CW8f15NbpslL8f38cw1JU2mqQYsIsMIv+hu2iNuCyT6ckWgPj2aBgRSb12NbuN9Cy7OrK7XQDCjksRJnjommD5HE58yFdu3Jx8VMNIjUrhqzhONQPych+sYwAJ1EsbxyZq1zqM1N8Fk0hN5B25YIQ9SEIE3m/LCvEX8IBAguEws36wO1PYjjfI8W6envtI2PZENt5ngB+bJpEWRhCLKmPAknZoC/Wk2tHDhExFP9XoqQwAcuZGjbpgO0rmAm+Dz4hjv33Y0998GvW2iKd0NFbXoSoOJLcGXsEZdHwIDLmQJNIosC+YSsQiv6TD4s8NGHlwfeuLdqCD5aymocKpyVE4QbMownq5R1/bLqimRPKDID4hPSrIxUncAhDcrj5hWkOBrBVqI/QXs5/9UV2oFWJomy1/MQksbJf1pjIjH6pAZMqdG+XLYn/2/zo/KiFqRhX6Vpe9YNTPwqM0UKRaMR6o4Yueb4aqOFErSFPJbwi3BbSB4hPlE57KkxeZuYH+pJLTsPabA3Z9Usi20kh+7tM9LWPcim+hpdL/YykfTAeHIehY7oVPL1okelfXde82SjGXrc0fbg9slOB1NX7TReRHc4CCOv6i6AbOl5BFdEiuC4zdWTfMF0z1PN3dmBKoI94pQfy5ep1pBog55XirEhVcwpo1xPCgkw9CmVlQTUTQHgK8NKZgi+b0CLoIA0kCu17oc9yaRuGQ4wp0dqJy36hc0hjbMlZK9L1yxUi05I=
  template:
    metadata:
      labels:
        app: datavault-api
        managed-by: kubectl
      name: datavault-secret
      namespace: datavault-dev
    type: Opaque
