apiVersion: v1
kind: Secret
metadata:
  name: secret-name
  namespace: ns-name
  labels:
    app: app-name
    managed-by: kubectl # optional
type: Opaque
data:
  # API key for authentication requestes to the DATAvault API
  API_KEY: api-secret-here
  # Database connection string
  DB_URL: db-connectioon-string-here

